apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nestjs-template
  title: Nest.js Template
  description: Build a NestJS API with options for GraphQL
spec:
  owner: group:3sidedcube/platform
  type: service
  parameters:
    - title: Config
      properties:
        name:
          title: Name
          type: string
        description:
          title: Description
          type: string
      required:
        - name
        - description
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        cookiecutterCompat: true
        copyWithoutTemplating:
          - .github/**/*
        url: ../common/base
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}

    - id: fetch-nestjs
      name: Fetch Nest.js
      action: fetch:template
      input:
        cookiecutterCompat: true
        copyWithoutTemplating:
          - .github/**/*
        url: ./skeleton

    - id: create-repo
      name: Create repo
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoUrl: github.com?owner=3sidedcube&repo=${{ parameters.name }}
        defaultBranch: main
        repoVisibility: private

    - id: register-entity
      name: Register entity
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo'].output.repoContentsUrl }}
        catalogInfoPath: /.platform/backstage/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo'].output.remoteUrl }}
