apiVersion: backstage.io/v1alpha1
kind: {{ cookiecutter.entity_type }}
metadata:
  name: {{ cookiecutter.name }}
  description: {{ cookiecutter.description }}
  annotations:
    backstage.io/source-location: url:https://github.com/3sidedcube/{{ cookiecutter.name }}
    backstage.io/techdocs-ref: dir:../..
    github.com/project-slug: 3sidedcube/{{ cookiecutter.name }}
spec:
  owner: 3sidedcube/{{ cookiecutter.team }}
  {% if cookiecutter.entity_type == "Component" %}
  type: {{ cookiecutter.component_type }}
  lifecycle: production
  {% endif %}
