apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: generic-template
  title: Generic Template
  description: Create an empty project with base files
spec:
  owner: group:3sidedcube/platform
  type: service
  parameters:
    - title: Config
      properties:
        name:
          title: Name
          type: string
          description: This will be the name of the repository.
        description:
          title: Description
          type: string
          description: Some information to outline what this repository is.
        team:
          title: Team
          type: string
          description: The team that owns this repository.
          enum:
            - frontend
            - backend
            - ios
            - android
            - platform
        entity_type:
          title: Entity Type
          type: string
          description: A 'Component' belongs to a 'System' being an API, website, script, job, etc.
          default: Component
          enum:
            - System
            - Component
      required:
        - name
        - description
        - team
        - entity_type
      dependencies:
        entity_type:
          oneOf:
            - properties:
                entity_type:
                  enum:
                    - System
            - properties:
                entity_type:
                  enum:
                    - Component
                component_type:
                  title: Component Type
                  type: string
                  description: The purpose of the 'Component'.
                  default: service
                  enum:
                    - service
                    - function
                    - website
              required:
                - component_type

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        cookiecutterCompat: true
        copyWithoutTemplating:
          - .github/**/*
        templateFileExtension: true
        url: ../common/base
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          entity_type: ${{ parameters.entity_type }}
          component_type: ${{ parameters.component_type }}
          team: ${{ parameters.team }}

    - id: create-repo
      name: Create repo
      action: publish:github
      input:
        allowMergeCommit: false
        allowRebaseMerge: false
        description: ${{ parameters.description }}
        defaultBranch: main
        deleteBranchOnMerge: true
        hasWiki: false
        hasIssues: false
        protectDefaultBranch: false
        repoUrl: github.com?owner=3sidedcube&repo=${{ parameters.name }}
        repoVariables:
          BACKSTAGE_ENTITY: default/${{ parameters.entity_type }}/${{ parameters.name }}
        repoVisibility: private

    - id: register-entity
      name: Register entity
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo'].output.repoContentsUrl }}
        catalogInfoPath: /.platform/backstage/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo'].output.remoteUrl }}
