apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: generic-template
  title: Generic Template
  description: Create an empty project with base files
spec:
  owner: group:3sidedcube/platform
  type: service
  parameters:
    - title: Config
      properties:
        name:
          title: Name
          type: string
        description:
          title: Description
          type: string
        entity_type:
          title: Type
          type: string
          default: Component
          enum:
            - System
            - Component
      required:
        - name
        - description
        - entity_type
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        cookiecutterCompat: true
        copyWithoutTemplating:
          - .github/**/*
        url: ../common/base
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}

    - id: create-repo
      name: Create repo
      action: publish:github
      input:
        allowMergeCommit: false
        allowRebaseMerge: false
        defaultBranch: main
        deleteBranchOnMerge: true
        hasWiki: false
        hasIssues: false
        protectDefaultBranch: false
        repoUrl: github.com?owner=3sidedcube&repo=${{ parameters.name }}
        repoVisibility: private

    - id: register-entity
      name: Register entity
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo'].output.repoContentsUrl }}
        catalogInfoPath: /.platform/backstage/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo'].output.remoteUrl }}
